# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YWBQ0nXLoJpLaYyOgkI1XD_aXBrkt8v
"""

import streamlit as st
import tensorflow as tf
import numpy as np
import cv2
from PIL import Image
from tensorflow.keras.models import load_model

# Load Model
model = load_model('/content/drive/MyDrive/SKRIPSI/Dataset/model.h5')

# Label Kelas (sesuaikan dengan dataset Anda)
class_names = ['Glioma_tumor', 'Meningioma_tumor', 'No_tumor', 'Pituitary_tumor']  # Ganti sesuai dengan nama kelas di dataset

# Fungsi Prediksi
def predict_image(image):
    image = image.resize((299, 299))  # Sesuaikan dengan ukuran input model
    image = np.array(image) / 255.0   # Normalisasi
    image = np.expand_dims(image, axis=0)  # Tambah dimensi batch

    prediction = model.predict(image)
    predicted_class = np.argmax(prediction)  # Ambil indeks kelas tertinggi
    confidence = np.max(prediction)  # Probabilitas tertinggi

    return class_names[predicted_class], confidence

# Streamlit UI
st.title("Klasifikasi Gambar dengan InceptionV3")
st.write("Upload gambar untuk diklasifikasikan oleh model.")

uploaded_file = st.file_uploader("Upload Gambar", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Gambar yang diunggah", use_column_width=True)

    if st.button("Prediksi"):
        label, conf = predict_image(image)
        st.success(f"Hasil Prediksi: **{label}** dengan confidence **{conf:.2f}**")

