# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJlsKQyizQ33_1bd0bDyQlHW_9b7L26n
"""

import streamlit as st
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torchvision import models
from PIL import Image
import numpy as np
import gdown
import os

# URL Google Drive untuk model (GANTI dengan ID yang benar)
url = "https://drive.google.com/uc?id=1sEeIy88VOdbWcMFWhUuoIXR5PeKshoMW"
model_path = "model_resnet18.pth"

# Fungsi untuk mendownload model jika belum ada
@st.cache_resource
def load_trained_model():
    if not os.path.exists(model_path):
        gdown.download(url, model_path, quiet=False)

    model = models.resnet18(pretrained=False)  # Gunakan arsitektur yang sama
    num_ftrs = model.fc.in_features
    model.fc = nn.Linear(num_ftrs, 4)  # Sesuaikan dengan jumlah kelas
    model.load_state_dict(torch.load(model_path, map_location=torch.device("cpu")))
    model.eval()  # Mode inferensi
    return model

# Load Model
model = load_trained_model()

# Label Kelas
class_names = ['Glioma_tumor', 'Meningioma_tumor', 'No_tumor', 'Pituitary_tumor']

# Transformasi gambar
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Fungsi Prediksi
def predict_image(image):
    image = transform(image).unsqueeze(0)  # Preprocessing
    with torch.no_grad():
        outputs = model(image)
        _, predicted = torch.max(outputs, 1)
        confidence = torch.nn.functional.softmax(outputs, dim=1)[0][predicted].item()

    return class_names[predicted], confidence

# Streamlit UI
st.title("Klasifikasi MRI Tumor Otak dengan ResNet18")
st.write("Upload gambar MRI untuk diklasifikasikan oleh model.")

uploaded_file = st.file_uploader("Upload Gambar", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Gambar yang diunggah", width=300)  # Diperkecil ukurannya

    if st.button("Prediksi"):
        label, conf = predict_image(image)
        st.success(f"Hasil Prediksi: **{label}** dengan confidence **{conf:.2f}**")

# Tambahkan nama di pojok kiri bawah
st.markdown(
    """
    <style>
        .footer {
            position: fixed;
            bottom: 10px;
            left: 10px;
            font-size: 12px;
            color: gray;
        }
    </style>
    <div class="footer">Dibuat oleh Nama Kamu</div>
    """,
    unsafe_allow_html=True
)