"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YWBQ0nXLoJpLaYyOgkI1XD_aXBrkt8v
"""

import streamlit as st
import tensorflow as tf
import numpy as np
import cv2
from PIL import Image
from tensorflow.keras.models import load_model

url = "https://drive.google.com/uc?id=1aBcD_EFGhijklMNOpQrS"
output = "model.h5"

@st.cache_resource  # Cache model agar tidak di-download berulang kali
def load_trained_model():
    gdown.download(url, output, quiet=False)  # Download dari Google Drive
    return load_model(output)

# Load Model
model = load_trained_model()
class_names = ['Glioma_tumor', 'Meningioma_tumor', 'No_tumor', 'Pituitary_tumor']  

def predict_image(image):
    image = image.resize((299, 299))  
    image = np.array(image) / 255.0   
    image = np.expand_dims(image, axis=0)  

    prediction = model.predict(image)
    predicted_class = np.argmax(prediction) 
    confidence = np.max(prediction) 
    return class_names[predicted_class], confidence

st.title("Klasifikasi Gambar dengan InceptionV3")
st.write("Upload gambar untuk diklasifikasikan oleh model.")

uploaded_file = st.file_uploader("Upload Gambar", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Gambar yang diunggah", use_column_width=True)

    if st.button("Prediksi"):
        label, conf = predict_image(image)
        st.success(f"Hasil Prediksi: **{label}** dengan confidence **{conf:.2f}**")

